// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// GO2gene
RcppExport List GO2gene(const DataFrame& Sdata);
RcppExport SEXP _GSminer_GO2gene(SEXP SdataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type Sdata(SdataSEXP);
    rcpp_result_gen = Rcpp::wrap(GO2gene(Sdata));
    return rcpp_result_gen;
END_RCPP
}
// elemLen1
IntegerVector elemLen1(const List& l);
RcppExport SEXP _GSminer_elemLen1(SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(elemLen1(l));
    return rcpp_result_gen;
END_RCPP
}
