# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GO2gene <- function(Sdata) {
    .Call('_GSminer_GO2gene', PACKAGE = 'GSminer', Sdata)
}

elemLen1 <- function(l) {
    .Call('_GSminer_elemLen1', PACKAGE = 'GSminer', l)
}

